Remove-Item -r .\docs
Copy-Item template .\docs -Recurse
Remove-Item .\docs\template.html
bookgen convert md2html --svg -i .\src\changelog.md -tf .\template\template.html -o .\docs --title "Changelog"
bookgen convert md2html --svg -i .\src\000-start.md -tf .\template\template.html -o .\docs\index.html --title "Home"
bookgen convert md2html --svg -i .\src\010-basiccommands.md -tf .\template\template.html -o .\docs --title "Dotnet basic commands"
bookgen convert md2html --svg -i .\src\020-project.md -tf .\template\template.html -o .\docs --title "Project file XML settings"
bookgen convert md2html --svg -i .\src\030-powershell.md -tf .\template\template.html -o .\docs --title "Usefull Powershell commands & scripts"
bookgen convert md2html --svg -i .\src\035-csharpbasics.md -tf .\template\template.html -o .\docs --title "C# basics"
bookgen convert md2html --svg -i .\src\040-types.md -tf .\template\template.html -o .\docs --title "Basic type system"
bookgen convert md2html --svg -i .\src\045-type-interfaces.md -tf .\template\template.html -o .\docs  --title "Important interfaces for types"
bookgen convert md2html --svg -i .\src\060-strings.md -tf .\template\template.html -o .\docs --title "Strings"
bookgen convert md2html --svg -i .\src\070-exceptions.md -tf .\template\template.html -o .\docs --title "Exceptions"
bookgen convert md2html --svg -i .\src\075-generics.md -tf .\template\template.html -o .\docs --title "Generics"
bookgen convert md2html --svg -i .\src\080-collections.md -tf .\template\template.html -o .\docs --title "Collections"
bookgen convert md2html --svg -i .\src\090-linq.md -tf .\template\template.html -o .\docs --title "LINQ"
bookgen convert md2html --svg -i .\src\095-regex.md -tf .\template\template.html -o .\docs --title "Regular Expressions"
bookgen convert md2html --svg -i .\src\100-paternmatch.md -tf .\template\template.html -o .\docs --title "Pattern Matching"
bookgen convert md2html --svg -i .\src\105-tasks.md -tf .\template\template.html -o .\docs --title "Tasks"
bookgen convert md2html --svg -i .\src\110-io.md -tf .\template\template.html -o .\docs --title "Input/Output"
bookgen convert md2html --svg -i .\src\111-attribs.md -tf .\template\template.html -o .\docs --title "Attributes"
bookgen convert md2html --svg -i .\src\112-serialization.md -tf .\template\template.html -o .\docs --title "Serialization"
bookgen convert md2html --svg -i .\src\114-validation.md -tf .\template\template.html -o .\docs --title "Validation"
bookgen convert md2html --svg -i .\src\120-crypto.md -tf .\template\template.html -o .\docs --title "Cryptography"
bookgen convert md2html --svg -i .\src\130-reflection.md -tf .\template\template.html -o .\docs --title "Reflection"
bookgen convert md2html --svg -i .\src\140-ui.md -tf .\template\template.html -o .\docs --title "UI"
bookgen convert md2html --svg -i .\src\150-nuget.md -tf .\template\template.html -o .\docs --title "Useful NuGet packagest"
bookgen convert md2html --svg -i .\src\155-shortcuts.md -tf .\template\template.html -o .\docs --title "Keyboard Shortcuts"
bookgen convert md2html --svg -i .\src\160-csharp-versions.md -tf .\template\template.html -o .\docs --title "C# Version History"